jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines456123forAlphabeticalArrayNumeralsAndOtherSymbol$'

#server:
#  port: 8080
#  error:
#    whitelabel:
#      enabled: false
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop_database
    username: root
    password: root
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  mvc:
#    throw-exception-if-no-handler-found: true
#  resources:
#    add-mappings: false

